'use client';

import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';
import { getSession, GetSessionParams } from 'next-auth/react';

import type { Session } from 'next-auth';
import { client, GET_TASKS } from '@/apolloClient';

const inter = Inter({ subsets: ['latin'] });
export async function getServerSideProps(
  context: GetSessionParams | undefined
) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/auth/signin',
        permanent: false,
      },
    };
  }
  // const { data } = await client.query({ query: GET_TASKS });

  return {
    props: {
      session,
      // data,
    },
  };
}

interface IndexPageProps {
  session: Session | null;
}

import { useQuery } from '@apollo/client';

export default function Home({ session, data }: IndexPageProps) {
  console.log(session, 'zaa');
  // const { data } = useQuery(GET_TASKS);
  // console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}></main>
    </>
  );
}
